### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by black-coda** [IfeOlulesi/EventsQA-backend#1]
I will love to contribute to the project, still waiting for you to upload stuff, sorry for opening issues, even when there is none.

**Comment by IfeOlulesi** [comment]
You're welcome @black-coda

**Comment by black-coda** [comment]
Thanks, waiting for you to create an app @IfeOlulesi

**Comment by IfeOlulesi** [comment]
Yeah, I have actually.
I'm yet to push it. Will do so this evening.

**Comment by IfeOlulesi** [comment]
So, I've done so.
Could you send me your telegram number at ifeolulesi@gmail.com
